# Generated by Django 4.2.6 on 2024-09-07 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(help_text="O'lcham: 371x202 px", upload_to='service/')),
                ('book_image', models.ImageField(help_text="O'lcham 160x250 px", upload_to='book/image/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='book/file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.service')),
            ],
        ),
    ]
